name = "ACE3"
prefix = "ace"
author = "ACE-Team"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "docs/README_*.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_ace3_ca.paa",
    "meta.cpp",
]

[version]
git_hash = 0

# TODO Enable once templating is added in v0.10
#[properties]
#version = "{{git \"id 8\"}}"

[asc]
enabled = true
exclude = [
    "/initsettings.sqf",
    "/initkeybinds.sqf",
    "/xeh_prep.sqf",
    "dev",
    "medical_ai/statemachine.sqf",
    "common/functions/fnc_dummy.sqf",
]

[hemtt.config]
preset = "Hemtt" # TODO will change after v0.10-a14
